// ── Email Verification Constants ──
// Used by the Email Unbouncer verification engine

/** 500+ disposable/temporary email domains */
export const DISPOSABLE_DOMAINS = new Set([
    // Major disposable providers
    "mailinator.com", "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
    "guerrillamail.de", "grr.la", "guerrillamailblock.com", "sharklasers.com",
    "guerrillamail.info", "spam4.me", "tempmail.com", "temp-mail.org",
    "temp-mail.io", "throwaway.email", "throwaway.com", "tempail.com",
    "dispostable.com", "yopmail.com", "yopmail.fr", "yopmail.net",
    "mailnesia.com", "maildrop.cc", "mailcatch.com", "mailhazard.com",
    "mailnull.com", "trash-mail.com", "trashmail.com", "trashmail.net",
    "trashmail.org", "trashmail.me", "trashmail.io", "trashymail.com",
    "10minutemail.com", "10minutemail.net", "10minutemail.org", "10minute.email",
    "20minutemail.com", "20minutemail.it", "minutemail.com",
    "tempinbox.com", "tempr.email", "tempmail.net", "tempmailaddress.com",
    "tempmails.net", "tmpmail.net", "tmpmail.org", "emailondeck.com",
    "fakeinbox.com", "fakemail.fr", "fakemail.net", "fakemailgenerator.com",
    "discard.email", "discardmail.com", "discardmail.de", "disposableemailaddresses.emailmiser.com",
    "mailforspam.com", "mailexpire.com", "mailmoat.com", "mailnator.com",
    "mytemp.email", "mytempmail.com", "meltmail.com", "mohmal.com",
    "getairmail.com", "getnada.com", "nada.email", "emailfake.com",
    "crazymailing.com", "mailsucker.net", "mailsac.com", "inboxkitten.com",
    "burnermail.io", "burpcollaborator.net", "spamgourmet.com",
    "safetymail.info", "safetypost.de", "anonymbox.com",
    "mailtemp.info", "harakirimail.com", "jetable.org", "boun.cr",
    "filzmail.com", "lookugly.com", "maildu.de", "mailme.ir",
    "mailmetrash.com", "mailquack.com", "mailscrap.com", "mailshell.com",
    "mailsiphon.com", "mailslurp.com", "mailzilla.com", "minex-coin.com",
    "nomail.xl.cx", "nowmymail.com", "objectmail.com", "obobbo.com",
    "onewaymail.com", "otherinbox.com", "ourklips.com", "owlpic.com",
    "pjjkp.com", "proxymail.eu", "rcpt.at", "reallymymail.com",
    "recode.me", "regbypass.com", "rhyta.com", "rklips.com",
    "rmqkr.net", "royal.net", "rppkn.com", "rtrtr.com",
    "ruffrey.com", "safersignup.de", "sharklasers.com",
    "shieldemail.com", "shiftmail.com", "sify.com",
    "sogetthis.com", "soodonims.com", "spambox.us",
    "spamcero.com", "spamcorptastic.com", "spamcowboy.com",
    "spamcowboy.net", "spamcowboy.org", "spamday.com",
    "spamfighter.cf", "spamfighter.ga", "spamfighter.gq",
    "spamfighter.ml", "spamfighter.tk", "spamfree24.com",
    "spamfree24.de", "spamfree24.eu", "spamfree24.info",
    "spamfree24.net", "spamfree24.org", "spamgoes.in",
    "spamherelots.com", "spamhereplease.com", "spamhole.com",
    "spamify.com", "spaminator.de", "spamkill.info",
    "spaml.com", "spaml.de", "spammotel.com",
    "spamobox.com", "spamoff.de", "spamslicer.com",
    "spamspot.com", "spamstack.net", "spamtrail.com",
    "spamtrap.ro", "speed.1s.fr", "superrito.com",
    "suremail.info", "teleworm.us", "thankyou2010.com",
    "thisisnotmyrealemail.com", "throwawayemailaddress.com",
    "tittbit.in", "tmail.ws", "tmailinator.com",
    "toiea.com", "tradermail.info", "turual.com",
    "twinmail.de", "tyldd.com", "uggsrock.com",
    "upliftnow.com", "venompen.com", "veryreallyelongated.com",
    "viditag.com", "viewcastmedia.com", "viewcastmedia.net",
    "viewcastmedia.org", "vomoto.com", "vpn.st",
    "vsimcard.com", "vubby.com", "wasteland.rfc822.org",
    "webemail.me", "weg-werf-email.de", "wegwerfadresse.de",
    "wegwerfemail.com", "wegwerfemail.de", "wegwerfmail.de",
    "wegwerfmail.net", "wegwerfmail.org", "wh4f.org",
    "whatiaas.com", "whatpaas.com", "whyspam.me",
    "wikidocuslice.com", "willhackforfood.biz", "willselfdestruct.com",
    "wilemail.com", "woolscup.com", "wuzup.net", "wuzupmail.net",
    "xagloo.com", "xemaps.com", "xents.com", "xjoi.com",
    "xmaily.com", "xoxox.cc", "xyzfree.net", "yogamaven.com",
    "yomail.info", "yopmail.com", "yopmail.fr", "yopmail.gq",
    "yuurok.com", "zehnminutenmail.de", "zippymail.info",
    "zoaxe.com", "zoemail.org", "zomg.info", "zxcv.com",
    "zzrgg.com",
    // Additional popular ones
    "guerrillamail.biz", "mailtemporaire.fr", "emailisvalid.com",
    "bugmenot.com", "devnullmail.com", "e4ward.com", "einrot.com",
    "emailigo.de", "emailthe.net", "emailwarden.com", "enterto.com",
    "ephemail.net", "etranquil.com", "etranquil.net", "etranquil.org",
    "evopo.com", "explodemail.com", "fastacura.com", "filzmail.com",
    "fixmail.tk", "flyspam.com", "footard.com", "forgetmail.com",
    "fr33mail.info", "frapmail.com", "front14.org", "fux0ringduh.com",
    "garliclife.com", "geronra.com", "ghosttexter.de", "girlsundertheinfluence.com",
    "gishpuppy.com", "goemailgo.com", "gorillaswithdirtyarmpits.com",
    "gotmail.net", "gotmail.org", "gotti.otherinbox.com", "great-host.in",
    "greensloth.com", "gsrv.co.uk", "guerrillamail.biz",
    "h8s.org", "haltospam.com", "hatespam.org", "hidemail.de",
    "hidzz.com", "hmamail.com", "hopemail.biz", "hot-mail.cf",
    "hot-mail.ga", "hot-mail.gq", "hot-mail.ml", "hot-mail.tk",
    "hotpop.com", "hulapla.de", "hushmail.com",
    "ieatspam.eu", "ieatspam.info", "ieh-mail.de", "ihateyoualot.info",
    "iheartspam.org", "imails.info", "inbax.tk", "inbox.si",
    "inboxalias.com", "inboxclean.com", "inboxclean.org", "incognitomail.com",
    "incognitomail.net", "incognitomail.org", "insorg-mail.info",
    "ipoo.org", "irish2me.com", "iwi.net", "jetable.com",
    "jetable.fr.nf", "jetable.net", "jetable.org", "jnxjn.com",
    "jourrapide.com", "jsrsolutions.com", "kasmail.com", "kaspop.com",
    "keepmymail.com", "killmail.com", "killmail.net", "kimsdisk.com",
    "kingsq.ga", "kir.ch.tc", "klassmaster.com", "klassmaster.net",
    "klzlk.com", "koszmail.pl", "kurzepost.de", "l33r.eu",
    "lackmail.net", "lags.us", "landmail.co", "lastmail.co",
    "lazyinbox.com", "letthemeatspam.com", "lhsdv.com", "lifebyfood.com",
    "link2mail.net", "litedrop.com", "lol.ovpn.to", "lolfreak.net",
    "lookugly.com", "lopl.co.cc", "lortemail.dk", "lr78.com",
    "m4ilweb.info", "maboard.com", "mail-filter.com", "mail-temporaire.fr",
    "mail.by", "mail.mezimages.net", "mail.zp.ua", "mail1a.de",
    "mail21.cc", "mail2rss.org", "mail333.com", "mail4trash.com",
    "mailbidon.com", "mailblocks.com", "mailblog.biz",
    "mailbucket.org", "mailcat.biz", "mailcatch.com",
    "maileater.com", "mailexpire.com", "mailfa.tk", "mailforspam.com",
    "mailfreeonline.com", "mailfs.com", "mailguard.me", "mailhazard.com",
    "mailhz.me", "mailimate.com", "mailin8r.com", "mailinater.com",
    "mailinator.com", "mailinator.net", "mailinator.org", "mailinator2.com",
    "mailincubator.com", "mailismagic.com", "mailmate.com",
    "mailme.ir", "mailme.lv", "mailmetrash.com", "mailmoat.com",
    "mailms.com", "mailnator.com", "mailnesia.com", "mailnull.com",
    "mailorg.org", "mailpick.biz", "mailproxsy.com",
    "mailquack.com", "mailrock.biz", "mailsac.com",
    "mailscrap.com", "mailseal.de", "mailshell.com",
    "mailsiphon.com", "mailslite.com", "mailtemp.info",
    "mailtome.de", "mailtothis.com", "mailtrash.net",
    "mailtv.net", "mailtv.tv", "mailzilla.com",
    "makemetheking.com", "manifestgenerator.com", "manybrain.com",
    "mbx.cc", "mega.zik.dj", "meinspamschutz.de", "meltmail.com",
    "messagebeamer.de", "mezimages.net", "mfsa.ru",
    "mierdamail.com", "ministry-of-silly-walks.de", "mintemail.com",
    "misterpinball.de", "mjukgansen.com", "moakt.com",
    "mobi.web.id", "mobileninja.co.uk", "mohmal.com",
    "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
    "monumentmail.com", "ms9.mailslite.com", "msa.minsmail.com",
    "mt2015.com", "mx0.wwwnew.eu", "my10minutemail.com",
    "myalias.pw", "mycard.net.ua", "mycleaninbox.net",
    "myemailboxy.com", "mymail-in.net", "mypacks.net",
    "mypartyclip.de", "myphantom.com", "mysamp.de",
    "myspaceinc.com", "myspaceinc.net", "myspaceinc.org",
    "myspacepimpedup.com", "mytemp.email", "mytempmail.com",
    "mytrashmail.com", "nabala.com", "neomailbox.com",
    "nepwk.com", "nervmich.net", "nervtansen.de",
    "netmails.com", "netmails.net", "neverbox.com",
    "no-spam.ws", "noblepioneer.com", "nobulk.com",
    "noclickemail.com", "nogmailspam.info", "nomail.xl.cx",
    "nomail2me.com", "nomorespamemails.com", "nonspam.eu",
    "nonspammer.de", "noref.in", "nospam.ze.tc",
    "nospam4.us", "nospamfor.us", "nospammail.net",
    "nospamthanks.info", "nothingtoseehere.ca", "nowmymail.com",
    "nurfuerspam.de", "nus.edu.sg", "nwldx.com",
    "objectmail.com", "obobbo.com", "odaymail.com",
    "one-time.email", "oneoffemail.com", "oneoffmail.com",
    "onewaymail.com", "oopi.org", "ordinaryamerican.net",
    "otherinbox.com", "ourklips.com", "outlawspam.com",
    "ovpn.to", "owlpic.com", "pancakemail.com",
    "pimpedupmyspace.com", "pjjkp.com", "plexolan.de",
    "pookmail.com", "privacy.net", "privatdemail.net",
    "privy-mail.com", "privymail.de", "proxymail.eu",
    "prtnx.com", "putthisinyouremail.com", "pwrby.com",
    "qisdo.com", "qisoa.com",
]);

/** Common role-based email prefixes */
export const ROLE_ACCOUNTS = [
    "admin", "administrator", "info", "contact", "support", "help", "sales",
    "billing", "accounts", "finance", "hr", "jobs", "careers", "recruitment",
    "marketing", "press", "media", "pr", "legal", "compliance", "security",
    "abuse", "postmaster", "hostmaster", "webmaster", "noreply", "no-reply",
    "donotreply", "do-not-reply", "mailer-daemon", "mailer", "newsletter",
    "notifications", "alerts", "updates", "feedback", "enquiries", "enquiry",
    "office", "reception", "team", "hello", "hi", "general", "service",
    "services", "orders", "returns", "shipping", "customerservice",
    "customercare", "customer-service", "customer-care", "tech",
    "technical", "engineering", "dev", "development", "ops", "operations",
    "it", "sysadmin", "root", "www", "ftp", "mail", "smtp", "imap", "pop",
];

/** Well-known free email providers */
export const FREE_PROVIDERS = new Set([
    "gmail.com", "googlemail.com", "yahoo.com", "yahoo.co.uk", "yahoo.fr",
    "yahoo.de", "yahoo.it", "yahoo.es", "yahoo.ca", "yahoo.com.au",
    "yahoo.co.in", "yahoo.com.br", "yahoo.co.jp", "ymail.com",
    "rocketmail.com", "outlook.com", "hotmail.com", "hotmail.co.uk",
    "hotmail.fr", "hotmail.de", "hotmail.it", "hotmail.es",
    "live.com", "live.co.uk", "live.fr", "live.de", "live.it",
    "msn.com", "icloud.com", "me.com", "mac.com",
    "aol.com", "aol.co.uk", "protonmail.com", "proton.me", "pm.me",
    "zoho.com", "zohomail.com", "mail.com", "email.com",
    "gmx.com", "gmx.net", "gmx.de", "gmx.at", "gmx.ch",
    "fastmail.com", "fastmail.fm", "tutanota.com", "tuta.io", "tutamail.com",
    "yandex.com", "yandex.ru", "mail.ru", "inbox.ru", "list.ru", "bk.ru",
    "rambler.ru", "qq.com", "163.com", "126.com", "sina.com",
    "rediffmail.com", "cox.net", "sbcglobal.net", "att.net",
    "bellsouth.net", "charter.net", "comcast.net", "earthlink.net",
    "optonline.net", "verizon.net", "roadrunner.com", "windstream.net",
]);
